version: '3'

services:
  onuryildizdev:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./pages:/onuryildiz.dev/pages
      - ./public:/onuryildiz.dev/public
      - ./styles:/onuryildiz.dev/styles
      - ./components:/onuryildiz.dev/components